### ISSUE TITLE
Criar Homepage

### ISSUE THREAD

**Issue by kaua-pt** [fga-eps-mds/2022-2-FGAtlas#15]
# Descrição 
Criar Homepage da aplicação com base no figma.

# Tarefas
[ ] Entrar no figma do squad;
[ ] Criar Homepage;

# Critérios de Aceitação
-Homepage completa;

**Comment by ccarlaa** [comment]
Homepage criada, porém será necessário realizar algumas alterações devido a retirada da parte de login.
Link do FIgma: https://www.figma.com/file/PUEGgHHGAdDTmObxylExzE/FGAtlas?node-id=0%3A1&t=b8fN31YH1LICg0ui-1
