### ISSUE TITLE
Terminar layout no figma

### ISSUE THREAD

**Issue by kaua-pt** [fga-eps-mds/2022-2-FGAtlas#16]
# Descrição 
Terminar layout do site no figma.

# Tarefas
[ ] Finalizar o layout

# Critérios de Aceitação
Layout finalizado.

**Comment by ccarlaa** [comment]
Página de listagem das matérias pronta.

**Comment by ccarlaa** [comment]
Fazer layout da página do mapa

**Comment by ccarlaa** [comment]
layout base finalizado
