### ISSUE TITLE
Estudar API do OpenStreetMap e realizar pequenos spikes

### ISSUE THREAD

**Issue by kaua-pt** [fga-eps-mds/2022-2-FGAtlas#28]
# Descrição
Estudar API do openStreetMap e realizar pequenos spikes

# Tarefas
[ ] Estudar API 
[ ] Realizar Spikes

**Comment by StrangeUnit28** [comment]
![image](https://user-images.githubusercontent.com/97995709/205518939-79249733-a80f-4e9a-8e7f-2bc0cc593d80.png)
Realizei um pequeno spike com a API go google maps;
Também testei a possibilidade de colocar marcadores e é bem tranquilo.
