### ISSUE TITLE
Criar GitPage

### ISSUE THREAD

**Issue by kaua-pt** [fga-eps-mds/2022-2-FGAtlas#46]
# Descrição
Criar o gitpage

# Tarefas
[] Criar o git page

**Comment by kaua-pt** [comment]
[GitPage script.docx](https://github.com/fga-eps-mds/2022-2-FGAtlas/files/10159664/GitPage.script.docx)
Segue um documento sobre oque deve estar na gitpage

**Comment by deboracaires** [comment]
GitPage finalizada -> https://fga-eps-mds.github.io/2022-2-FGAtlas/
