### ISSUE TITLE
Criar código de conduta, readme e contributing

### ISSUE THREAD

**Issue by kaua-pt** [fga-eps-mds/2022-2-FGAtlas#47]
# Descrição
Criar código de conduta, readme e Código de conduta 

# Tarefas
[ ] Código de conduta 
[ ] ReadMe
[ ] Contributing

# Critérios de aceitação
Os 3 documentos

**Comment by StrangeUnit28** [comment]
Guia de Contribuição e Código de Conduta feitos.

**Comment by StrangeUnit28** [comment]
README completo
