### ISSUE TITLE
Continuar HomePage

### ISSUE THREAD

**Issue by kaua-pt** [fga-eps-mds/2022-2-FGAtlas#51]
# Descrição
Continuar HomePage

# Tarefas
[ ] Continuar Homepage

# Critérios de aceitação
HomePage Pronta.

**Comment by ccarlaa** [comment]
Arrumar links para as respectivas rotas

**Comment by ccarlaa** [comment]
A página foi reorganizada para se encaixar com as requisições do back

**Comment by ccarlaa** [comment]
Colocar o nome do app

**Comment by ccarlaa** [comment]
finalizada
