### ISSUE TITLE
Revisão do README, CONTRIBUTING, CODE_OF_CONDUCT e Descrição

### ISSUE THREAD

**Issue by StrangeUnit28** [fga-eps-mds/2022-2-FGAtlas#61]
# Descrição
Revisar os documentos já feitos para evitar possíveis erros que passaram despercebidos.

# Tarefas
- [x] Revisar README
- [x] Revisar CONTRIBUTING
- [x] Revisar CODE_OF_CONDUCT
- [x] Revisar Descrição

# Critérios de aceitação
Todos os documentos listados devem ter sido revisados

**Comment by kaua-pt** [comment]
Código de contribuição, Contributing e descrição revisados
