### ISSUE TITLE
Montar Slide de apresentação

### ISSUE THREAD

**Issue by kaua-pt** [fga-eps-mds/2022-2-FGAtlas#68]
# Descrição
Montar slide para apresentação da r1

# Tarefas
[ ] Montar Slides
[ ] Apresentar ao grupo

# Critérios de aceitação
Slides montados

**Comment by sabrinaberno** [comment]
Slides da apresentação ficaram prontos e foram validados pela equipe
[FGAtlas.pdf](https://github.com/fga-eps-mds/2022-2-FGAtlas/files/10231593/FGAtlas.pdf)
