### ISSUE TITLE
Extender Scapper para o departamento de matemática e para o departamento de CIC

### ISSUE THREAD

**Issue by kaua-pt** [fga-eps-mds/2022-2-FGAtlas#71]
# Descrição
Fazer o webScrapping das matérias do departamento de matemática

# Tarefas
[ ] Departamento de matemática
[ ] Departamento de CIC

# Critérios de aceitação
Array com os dados do departamento de matemática e outro com os dados do departamento de CIC

**Comment by StrangeUnit28** [comment]
Comecei a fazer a extensão do WebScreapper
